[package]
name = "atari_demon_attack"
version = "0.1.0"
authors = ["TanTanDev <mrjonatanOlsson@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
macroquad = "0.3.0-alpha.15"